# Generated by Django 5.1.4 on 2024-12-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_topping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'toppings'},
        ),
    ]
