guest_list = ['dad', 'grandpa', 'grandma']
print(f"{guest_list[0].title()}, you are invited to dinner!")
print(f"So are you {guest_list[1].title()}")
print(f"I wouldn't forget {guest_list[2].title()}, so much fun!")
print(f"We'll be having {len(guest_list)} guests over for dinner!")
print(f"Wait ... unfortunately {guest_list[1].title()} can't make it :(")
guest_list[1] = "hatred"
print(f"{guest_list[0].title()}, you are invited to dinner!")
print(f"So are you {guest_list[1].title()}")
print(f"I wouldn't forget {guest_list[2].title()}, so much fun!")
print("We found a bigger table! We'll be inviting more people!")
guest_list.insert(0, "bob")
guest_list.insert(2, "susan")
guest_list.append("Andrew")
print(f"We'll be having {len(guest_list)} guests over for dinner!")
print(guest_list)
print("Bummer, turns out we can only invite two people :(")
uninvited = guest_list.pop()
print(f"Unfortunately {uninvited} won't be joining us")
uninvited = guest_list.pop()
print(f"Unfortunately {uninvited} won't be joining us")
uninvited = guest_list.pop()
print(f"Unfortunately {uninvited} won't be joining us")
uninvited = guest_list.pop()
print(f"Unfortunately {uninvited} won't be joining us")
print(f"You are still invited {guest_list[0].title()}")
print(f"You are still invited {guest_list[1].title()}")
print(f"We'll be having {len(guest_list)} guests over for dinner!")
del guest_list[0]
del guest_list[0]
print(f"We'll be having {len(guest_list)} guests over for dinner!")
print(guest_list)